name: Staging

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Version
        run: echo "MY_VERSION=v1.5.0" >> $GITHUB_ENV

      - name: Print Version
        run: echo "The version is $MY_VERSION"
