name: CI-WORKFLOW
on: branch_protection_rule

jobs: 
   build-test:
      runs-on: ubuntu-22.04
      steps:
         - name: build
           uses: actions/checkout@v7
         - name: test
           run: npm install
         - name: artifact upload
           uses: actions/upload-artifact@v7
           with:
              name: artifact-1
              path: | 
                 package*
         - name: deploy
           run: echo "deployment is completed"
      
