name: ganesh-project
on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: |
            package.json
            package-lock.json

      - name: Deploy
        run: echo "Application deployed"
