name: NodeJs



on:
  push:
    branches:
      - master
permissions:
  contents: read
  actions: read
  security-events: write
jobs:
  Build-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - run: npm install

      - run: npm test

      - uses: github/codeql-action/analyze@v4

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-1
          path: package*

      - run: echo "Code deployed"
